
users = """
CREATE TABLE users (
id SERIAL PRIMARY KEY,
username VARCHAR(50) UNIQUE NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
password TEXT NOT NULL,
is_login BOOLEAN DEFAULT FALSE,
is_active BOOLEAN DEFAULT FALSE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""
posts = """
CREATE TABLE posts (
id SERIAL PRIMARY KEY,
user_id INT REFERENCES users(id) ON DELETE CASCADE,
post TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

likes = """
CREATE TABLE IF NOT EXISTS likes (
ID SERIAL PRIMARY KEY,
user_id INT REFERENCES users(ID) ON DELETE CASCADE,
post_id INT REFERENCES posts(ID) ON DELETE CASCADE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""
codes = """
CREATE TABLE IF NOT EXISTS codes (
id SERIAL PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE,
code VARCHAR(6),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""